// 命令清单只为 ACL：这四条在 Rust 侧**没有**对应 command——JS 直接 invoke 到 Swift
// （tauri 的 webview/mod.rs：插件里没登记的命令在移动端会转给原生插件 run_command，命令名转 lowerCamelCase）。
// 声明在这里 → permissions/autogenerated 生成 allow-* → capabilities/mobile.json 的 "iap:default" 才放得开。
const COMMANDS: &[&str] = &["products", "purchase", "restore", "entitlements"];

fn main() {
    // ios_path：目标是 iOS 时由 swift-rs 把 ios/ 这个 Swift 包编成静态库链进来（tauri-plugin 的 mobile::setup）；
    // 桌面/Windows 上这一步是空操作，只生成权限文件——所以本机 cargo check 能验 Rust 半边，Swift 半边只有 CI 能验。
    tauri_plugin::Builder::new(COMMANDS).ios_path("ios").build();
}
